#pragma once

/* Status Parameters for database connections (from sqlite3.h) */
enum {
  SQLITE_DBSTATUS_LOOKASIDE_USED = 0,
  SQLITE_DBSTATUS_CACHE_USED = 1,
  SQLITE_DBSTATUS_SCHEMA_USED = 2,
  SQLITE_DBSTATUS_STMT_USED = 3,
  SQLITE_DBSTATUS_LOOKASIDE_HIT = 4,
  SQLITE_DBSTATUS_LOOKASIDE_MISS_SIZE = 5,
  SQLITE_DBSTATUS_LOOKASIDE_MISS_FULL = 6,
  SQLITE_DBSTATUS_CACHE_HIT = 7,
  SQLITE_DBSTATUS_CACHE_MISS = 8,
  SQLITE_DBSTATUS_CACHE_WRITE = 9,
  SQLITE_DBSTATUS_DEFERRED_FKS = 10,
  SQLITE_DBSTATUS_CACHE_USED_SHARED = 11,
  SQLITE_DBSTATUS_CACHE_SPILL = 12,
  SQLITE_DBSTATUS_TEMPBUF_SPILL = 13,
  SQLITE_DBSTATUS_MAX = 13, /* Largest defined DBSTATUS */
};


