#pragma once
#ifdef __cplusplus
extern "C" {
#endif
/* Standard File Control Opcodes (from sqlite3.h) */
enum {
  SQLITE_FCNTL_LOCKSTATE = 1,
  SQLITE_FCNTL_GET_LOCKPROXYFILE = 2,
  SQLITE_FCNTL_SET_LOCKPROXYFILE = 3,
  SQLITE_FCNTL_LAST_ERRNO = 4,
  SQLITE_FCNTL_SIZE_HINT = 5,
  SQLITE_FCNTL_CHUNK_SIZE = 6,
  SQLITE_FCNTL_FILE_POINTER = 7,
  SQLITE_FCNTL_SYNC_OMITTED = 8,
  SQLITE_FCNTL_WIN32_AV_RETRY = 9,
  SQLITE_FCNTL_PERSIST_WAL = 10,
  SQLITE_FCNTL_OVERWRITE = 11,
  SQLITE_FCNTL_VFSNAME = 12,
  SQLITE_FCNTL_POWERSAFE_OVERWRITE = 13,
  SQLITE_FCNTL_PRAGMA = 14,
  SQLITE_FCNTL_BUSYHANDLER = 15,
  SQLITE_FCNTL_TEMPFILENAME = 16,
  SQLITE_FCNTL_MMAP_SIZE = 18,
  SQLITE_FCNTL_TRACE = 19,
  SQLITE_FCNTL_HAS_MOVED = 20,
  SQLITE_FCNTL_SYNC = 21,
  SQLITE_FCNTL_COMMIT_PHASETWO = 22,
  SQLITE_FCNTL_WIN32_SET_HANDLE = 23,
  SQLITE_FCNTL_WAL_BLOCK = 24,
  SQLITE_FCNTL_ZIPVFS = 25,
  SQLITE_FCNTL_RBU = 26,
  SQLITE_FCNTL_VFS_POINTER = 27,
  SQLITE_FCNTL_JOURNAL_POINTER = 28,
  SQLITE_FCNTL_WIN32_GET_HANDLE = 29,
  SQLITE_FCNTL_PDB = 30,
  SQLITE_FCNTL_BEGIN_ATOMIC_WRITE = 31,
  SQLITE_FCNTL_COMMIT_ATOMIC_WRITE = 32,
  SQLITE_FCNTL_ROLLBACK_ATOMIC_WRITE = 33,
  SQLITE_FCNTL_LOCK_TIMEOUT = 34,
  SQLITE_FCNTL_DATA_VERSION = 35,
  SQLITE_FCNTL_SIZE_LIMIT = 36,
  SQLITE_FCNTL_CKPT_DONE = 37,
  SQLITE_FCNTL_RESERVE_BYTES = 38,
  SQLITE_FCNTL_CKPT_START = 39,
  SQLITE_FCNTL_EXTERNAL_READER = 40,
  SQLITE_FCNTL_CKSM_FILE = 41,
  SQLITE_FCNTL_RESET_CACHE = 42,
  SQLITE_FCNTL_NULL_IO = 43,
  SQLITE_FCNTL_BLOCK_ON_CONNECT = 44,
  SQLITE_FCNTL_FILESTAT = 45,
  SQLITE_GET_LOCKPROXYFILE = SQLITE_FCNTL_GET_LOCKPROXYFILE,
  SQLITE_SET_LOCKPROXYFILE = SQLITE_FCNTL_SET_LOCKPROXYFILE,
  SQLITE_LAST_ERRNO = SQLITE_FCNTL_LAST_ERRNO,
};

#ifdef __cplusplus
}
#endif
