#pragma once
#ifdef __cplusplus
extern "C" {
#endif
/* Testing Interface Operation Codes (from sqlite3.h) */
enum {
  SQLITE_TESTCTRL_FIRST = 5,
  SQLITE_TESTCTRL_PRNG_SAVE = 5,
  SQLITE_TESTCTRL_PRNG_RESTORE = 6,
  SQLITE_TESTCTRL_PRNG_RESET = 7, /* NOT USED */
  SQLITE_TESTCTRL_FK_NO_ACTION = 7,
  SQLITE_TESTCTRL_BITVEC_TEST = 8,
  SQLITE_TESTCTRL_FAULT_INSTALL = 9,
  SQLITE_TESTCTRL_BENIGN_MALLOC_HOOKS = 10,
  SQLITE_TESTCTRL_PENDING_BYTE = 11,
  SQLITE_TESTCTRL_ASSERT = 12,
  SQLITE_TESTCTRL_ALWAYS = 13,
  SQLITE_TESTCTRL_RESERVE = 14, /* NOT USED */
  SQLITE_TESTCTRL_JSON_SELFCHECK = 14,
  SQLITE_TESTCTRL_OPTIMIZATIONS = 15,
  SQLITE_TESTCTRL_ISKEYWORD = 16, /* NOT USED */
  SQLITE_TESTCTRL_GETOPT = 16,
  SQLITE_TESTCTRL_SCRATCHMALLOC = 17, /* NOT USED */
  SQLITE_TESTCTRL_INTERNAL_FUNCTIONS = 17,
  SQLITE_TESTCTRL_LOCALTIME_FAULT = 18,
  SQLITE_TESTCTRL_EXPLAIN_STMT = 19, /* NOT USED */
  SQLITE_TESTCTRL_ONCE_RESET_THRESHOLD = 19,
  SQLITE_TESTCTRL_NEVER_CORRUPT = 20,
  SQLITE_TESTCTRL_VDBE_COVERAGE = 21,
  SQLITE_TESTCTRL_BYTEORDER = 22,
  SQLITE_TESTCTRL_ISINIT = 23,
  SQLITE_TESTCTRL_SORTER_MMAP = 24,
  SQLITE_TESTCTRL_IMPOSTER = 25,
  SQLITE_TESTCTRL_PARSER_COVERAGE = 26,
  SQLITE_TESTCTRL_RESULT_INTREAL = 27,
  SQLITE_TESTCTRL_PRNG_SEED = 28,
  SQLITE_TESTCTRL_EXTRA_SCHEMA_CHECKS = 29,
  SQLITE_TESTCTRL_SEEK_COUNT = 30,
  SQLITE_TESTCTRL_TRACEFLAGS = 31,
  SQLITE_TESTCTRL_TUNE = 32,
  SQLITE_TESTCTRL_LOGEST = 33,
  SQLITE_TESTCTRL_USELONGDOUBLE = 34, /* NOT USED */
  SQLITE_TESTCTRL_ATOF = 34,
  SQLITE_TESTCTRL_LAST = 34, /* Largest TESTCTRL */
};

#ifdef __cplusplus
}
#endif
