#pragma once
#ifdef __cplusplus
extern "C" {
#endif
/* Virtual Table Constraint Operator Codes (from sqlite3.h) */
enum {
  SQLITE_INDEX_CONSTRAINT_EQ = 2,
  SQLITE_INDEX_CONSTRAINT_GT = 4,
  SQLITE_INDEX_CONSTRAINT_LE = 8,
  SQLITE_INDEX_CONSTRAINT_LT = 16,
  SQLITE_INDEX_CONSTRAINT_GE = 32,
  SQLITE_INDEX_CONSTRAINT_MATCH = 64,
  SQLITE_INDEX_CONSTRAINT_LIKE = 65,
  SQLITE_INDEX_CONSTRAINT_GLOB = 66,
  SQLITE_INDEX_CONSTRAINT_REGEXP = 67,
  SQLITE_INDEX_CONSTRAINT_NE = 68,
  SQLITE_INDEX_CONSTRAINT_ISNOT = 69,
  SQLITE_INDEX_CONSTRAINT_ISNOTNULL = 70,
  SQLITE_INDEX_CONSTRAINT_ISNULL = 71,
  SQLITE_INDEX_CONSTRAINT_IS = 72,
  SQLITE_INDEX_CONSTRAINT_LIMIT = 73,
  SQLITE_INDEX_CONSTRAINT_OFFSET = 74,
  SQLITE_INDEX_CONSTRAINT_FUNCTION = 150,
};

#ifdef __cplusplus
}
#endif
